name: Deploy LawGIA to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 레포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Node.js 설치 (frontend 요구 >=20)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # 3. frontend 의존성 설치 및 빌드
      - name: Install and build frontend
        working-directory: ./app/frontend
        run: |
          npm install
          npm run build

      # 4. backend 준비 (필요한 경우 추가 명령어)
      - name: Prepare backend
        working-directory: ./app/backend
        run: |
          # 예: 필요 시 pip, npm 설치 등
          echo "Backend ready"

      # 5. 통합 배포용 패키지 준비
      - name: Prepare deployment package
        run: |
          # 기존 static 폴더 삭제 후 frontend 빌드 파일 복사
          rm -rf ./app/backend/static
          mkdir -p ./app/backend/static
          cp -r ./app/frontend/dist/* ./app/backend/static/

      # 6. Azure 로그인 (Publish Profile 사용)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 7. Azure Web App 배포
      - name: Deploy frontend + backend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'LawGIA'
          package: ./app/backend
